#!/usr/bin/env python3
"""Build the portable single-file Linux/macOS executable for ISO Package Manager.

The result is ``dist/iso-package-manager-<version>.pyz``: a self-contained
Python zipapp that starts with a ``#!/usr/bin/env python3`` shebang.  On
Linux/macOS the file *is* the program once it is marked executable::

    chmod +x dist/iso-package-manager-0.10.1.pyz
    ./dist/iso-package-manager-0.10.1.pyz          # asks UI or Terminal

On Windows it can still be run, which is what the build machine uses to
smoke-test the archive::

    python dist\\iso-package-manager-0.10.1.pyz --version

The ``themes/`` folder is baked in as ``<archive>/themes``, which
``ipm_themes.py`` reads straight out of the zip - so the one downloaded file
already has theme packs to pick from, with no extra ``themes`` folder needed.

Why a zipapp:

* it needs no compiler, no Linux machine and no extra packages - the same
  bytes are produced on every OS, so it can be built from Windows;
* startup is a plain ``python3`` run of the same modules used in the repo,
  so behaviour matches the source tree exactly;
* the only runtime requirement is python3 (3.10+) with tkinter, which every
  desktop Linux distribution ships (Debian/Ubuntu: ``python3-tk``).

For a fully native ELF binary with no Python dependency at all, run
``build_linux.sh`` on Linux, or ``build_linux_docker.sh`` where Docker is
available (see README).

Usage::

    python build_pyz.py                # build into ./dist
    python build_pyz.py --out dist     # choose the output directory
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import tempfile
import zipapp
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"
SLUG = "iso-package-manager"

ENTRY_MODULE = "ipm_launcher.py"

# Every module the launcher, the CLI and the Tk GUI import at runtime.  All of
# them are plain modules in the project root - there is no package directory to
# walk, which keeps the archive small and the contents explicit.
MODULES = (
    "ipm_launcher.py",
    "ipm_cli.py",
    "ipm_ia.py",
    "ipm_search.py",
    "ipm_utils.py",
    "ipm_http.py",
    "ipm_models.py",
    "ipm_windows.py",
    "ipm_winops.py",
    "main.py",
    # Optional, but without it the archive has no theme-pack support at all
    # (main.py imports it defensively, so a missing copy is silently ignored).
    "ipm_themes.py",
    "ipm_shop.py",
)

# Docs are tiny and make the archive self-describing.
EXTRAS = ("README.md", "SEARCH_GUIDE.md", "SECURITY.md")

# Theme packs are baked into the archive as <archive>/themes/<pack>.json.  That
# is the last entry in ipm_themes.search_paths(), so whatever the user installs
# later always wins - but a freshly downloaded .pyz still has themes to show.
THEMES_FOLDER = "themes"
THEMES_DIR = ROOT / THEMES_FOLDER

# zipapp normally generates a __main__.py that calls the entry point without
# propagating its return value, which would swallow exit codes (bad for
# `ipm-cli search ... || echo failed`).  A hand-written one keeps them.
MAIN_TEMPLATE = '''"""ISO Package Manager - zipapp entry point (generated by build_pyz.py)."""

import sys

try:
    import ipm_launcher
except ImportError as exc:  # pragma: no cover - broken/partial archive
    sys.stderr.write(
        "iso-package-manager: cannot import ipm_launcher from this archive (%s)\\n" % exc
    )
    sys.stderr.write("rebuild it with: python build_pyz.py\\n")
    raise SystemExit(1)

if __name__ == "__main__":
    raise SystemExit(ipm_launcher.main())
'''


def read_version() -> str:
    """Pull APP_VERSION out of the launcher so the filename always matches."""
    text = (ROOT / ENTRY_MODULE).read_text(encoding="utf-8", errors="replace")
    match = re.search(r'^APP_VERSION\s*=\s*["\']([^"\']+)["\']', text, re.MULTILINE)
    return match.group(1) if match else "0.0"


def build(out_dir: Path) -> Path:
    missing = [name for name in MODULES if not (ROOT / name).is_file()]
    if missing:
        raise SystemExit("missing project module(s): " + ", ".join(missing))

    version = read_version()
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{SLUG}-{version}.pyz"

    staging = Path(tempfile.mkdtemp(prefix="ipm_pyz_"))
    try:
        for name in MODULES:
            shutil.copy2(ROOT / name, staging / name)
        for name in EXTRAS:
            src = ROOT / name
            if src.is_file():
                shutil.copy2(src, staging / name)

        if THEMES_DIR.is_dir():
            staged_themes = staging / THEMES_FOLDER
            staged_themes.mkdir(parents=True, exist_ok=True)
            for pack in sorted(THEMES_DIR.glob("*.json")):
                if pack.is_file():
                    shutil.copy2(pack, staged_themes / pack.name)

        (staging / "__main__.py").write_text(MAIN_TEMPLATE, encoding="utf-8")

        # Skip __pycache__ inside the staging tree (copy2 above never creates
        # it, but a stale one from an interrupted run would be picked up).
        for cache in staging.rglob("__pycache__"):
            shutil.rmtree(cache, ignore_errors=True)

        if target.exists():
            target.unlink()

        zipapp.create_archive(
            source=staging,
            target=target,
            interpreter="/usr/bin/env python3",
            compressed=True,
        )
    finally:
        shutil.rmtree(staging, ignore_errors=True)

    # Make it executable when the filesystem supports it (no-op on Windows).
    try:
        mode = target.stat().st_mode
        target.chmod(mode | 0o111)
    except OSError:
        pass

    return target


def bundled_theme_count(archive: Path) -> int:
    """Pack files stored under ``themes/`` inside a finished archive."""
    prefix = THEMES_FOLDER + "/"
    try:
        with zipfile.ZipFile(archive) as handle:
            return sum(
                1
                for name in handle.namelist()
                if name.replace("\\", "/").lower().startswith(prefix)
                and name.lower().endswith(".json")
            )
    except (OSError, zipfile.BadZipFile):  # pragma: no cover - just built it
        return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the Linux/macOS single-file executable.")
    parser.add_argument("--out", default=str(DIST), help="output directory (default: ./dist)")
    args = parser.parse_args(argv)

    target = build(Path(args.out).expanduser().resolve())
    size = target.stat().st_size

    print(f"built: {target}")
    print(f"  size:        {size:,} bytes")
    print(f"  themes:      {bundled_theme_count(target)} theme pack(s) bundled inside")
    print(f"  interpreter: /usr/bin/env python3   (needs python3 >= 3.10 + tkinter)")
    print()
    print("  Linux / macOS:")
    print(f"    chmod +x {target.name}")
    print(f"    ./{target.name}                       (asks: UI or Terminal)")
    print(f"    ./{target.name} --cli search ubuntu")
    print(f"    ./{target.name} --gui")
    print()
    print("  Windows (archive smoke test):")
    print(f"    python {target}")
    print()
    print("  Native ELF with no Python dependency: run build_linux.sh on Linux.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
